GET http://localhost:2001/api/todos

###

POST  http://localhost:2001/api/todos/new
Content-Type: application/json


{
    "text":"Get the information"
}

###

DELETE http://localhost:2001/api/todos/delete/64ddd1314d9d8482697cac25


###

GET http://localhost:2001/api/todos/complete/64ddd1364d9d8482697cac27